server:
  port: 80
debug: false
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ta?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=0&serverTimezone=UTC
    username: root
    password: kingston
  thymeleaf:
    cache: false
    mode: HTML
  mvc:
    favicon:
      enabled: false
  output:
    ansi:
      enabled: detect #控制台多彩输出
  http:
    multipart:
      location: C:/Users/Ning/Desktop/upload/ #文件上传路径
  resources:
    static-locations: /META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:${spring.http.multipart.location}
logging:
  level: error